# Generated by Django 2.1 on 2019-03-30 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_auto_20190330_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='task_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
