# Generated by Django 2.1 on 2019-03-30 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0003_todolist_task_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='task_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
