# Generated by Django 2.1 on 2019-03-30 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0005_auto_20190330_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='status',
            field=models.TextField(max_length=50),
        ),
    ]
