# Generated by Django 2.1 on 2019-04-01 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0006_auto_20190330_2238'),
    ]

    operations = [
        migrations.CreateModel(
            name='MangedDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_start_time', models.TextField(max_length=100)),
                ('content', models.TextField(blank=True, max_length=256, null=True)),
                ('status', models.TextField(blank=True, max_length=50, null=True)),
                ('category', models.TextField(blank=True, max_length=50, null=True)),
                ('priority', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
    ]
